- name: install nginx server
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:  # to install a package/service # Heterogeneous module that can work for all distributions
      name: nginx
      state: absent
  - name: start nginx service
    ansible.builtin.service:  # to start a package/service
      name: nginx
      state: started
