- name: varaiable to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "120 HOURS"
    TRAINER: "SivaKumar"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am Learning: {{COURSE}}, [[DURATION]] is: 120HRS, Trainer: [[TRAINER]]"