- name: varaiable at play and task level
  hosts: web
  vars:   # play level, all tasks in this file/play have access to this
    COURSE: "DevOps with AWS"
    DURATION: "120 HOURS"
    TRAINER: "SivaKumar"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am Learning: {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

# task level variables override play level
  - name: print the information again
    vars: 
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, I am Learning: {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

# this variable will take values from play level
  - name: print the information again and again
    ansible.builtin.debug:
      msg: "Hi, I am Learning: {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

