- name: variables from inventory
  host: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am Learning: {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"