- name: variables from inventory
  hosts: web    # vars from inventory
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am Learning: {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"