- name: varaiable at play level
  hosts: web
  # vars:   # play level, all tasks in this file/play have access to this
  #   COURSE: "DevOps with AWS from play level"
  #   DURATION: "120 HOURS"
  #   TRAINER: "SivaKumar"
# Variables from files
  # vars_files:
  # - vars.yaml
# Variables from prompt
  # vars_prompt:    # prompts the value
  # - name: COURSE
  #   prompt: please enter the course name
  #   private: false    # not confidential
# task level variables override play level
  # tasks:
  # - name: print the information
  #   vars: 
  #     # COURSE: "DevOps with AWS from task level"
  #     DURATION: "120 HOURS"
  #     TRAINER: "SivaKumar"
  #   ansible.builtin.debug:
  #     msg: "Hi, I am Learning: {{COURSE}}"

#1. Command line/Args
#2. Task level
#3. var fiels
#4. Prompt
#5. Play level
#6. 