- name: demo on filter/functions
  hosts: local
  connection: local
  tasks:
  - name: print default variable
    ansible.builtin.debug:
      msg: "Hello {{ name | default('Ramesh') }}"   # Providing default values by ingnoring undefined variables.
      
  - name: convert to uppercase
    vars:
      greeting: hello ramesh
    ansible.builtin.debug:
     msg: "{{greeting | upper}}"   # Upper case
   
  - name: convert to uppercase
    vars:
      greeting: HELLO RAMESH
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"    # Lower case


     
