- name: create ec2 and r53 records
  hosts: loca
  connection: local
  vars:
    subnet_id: "vpc-08130555fc639bd04"
    sg_id: "sg-0f1b4e3ba768d34aa"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}"
      vpc_subnet_id: "{{subnet_id}}"
      security_group: "{{sg_id}}"
      image_id: "{{ami_id}}"
    loop: "{{instances}}"
    register: ec2_instance    # to capture the output of a task


